# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moment_OP_2nd_rcpp <- function(T, J, alpha, beta_0, beta_k, y_error_tilde, phi_t_1, matA) {
    .Call('_EstProduct_moment_OP_2nd_rcpp', PACKAGE = 'EstProduct', T, J, alpha, beta_0, beta_k, y_error_tilde, phi_t_1, matA)
}

rcppeigen_hello_world <- function() {
    .Call('_EstProduct_rcppeigen_hello_world', PACKAGE = 'EstProduct')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_EstProduct_rcppeigen_outerproduct', PACKAGE = 'EstProduct', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_EstProduct_rcppeigen_innerproduct', PACKAGE = 'EstProduct', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_EstProduct_rcppeigen_bothproducts', PACKAGE = 'EstProduct', x)
}

